import { CSSProperties } from 'react';
export type FormTheme = {
    primary: string;
    primaryHover: string;
    primaryLight: string;
    primaryLighter: string;
    alertBg: string;
    alertBorder: string;
    alertText: string;
    alertTitle: string;
};
export declare const themes: Record<string, FormTheme>;
export declare const makeStyles: (theme: FormTheme) => {
    page: CSSProperties;
    container: CSSProperties;
    pageHeader: CSSProperties;
    brandName: CSSProperties;
    brandSub: CSSProperties;
    stepBadge: CSSProperties;
    progressTrack: CSSProperties;
    card: CSSProperties;
    cardBody: CSSProperties;
    cardFooter: CSSProperties;
    alertBox: CSSProperties;
    alertTitle: CSSProperties;
    alertText: CSSProperties;
    sectionTitle: CSSProperties;
    sectionSub: CSSProperties;
    group: CSSProperties;
    label: CSSProperties;
    helpText: CSSProperties;
    input: CSSProperties;
    textarea: CSSProperties;
    select: CSSProperties;
    radioCard: (selected: boolean) => CSSProperties;
    btnPrev: CSSProperties;
    btnNext: CSSProperties;
    btnSubmit: CSSProperties;
    btnAddMore: CSSProperties;
    itemCard: CSSProperties;
    itemCardHeader: CSSProperties;
    itemCardBody: CSSProperties;
    grid2: CSSProperties;
    grid3: CSSProperties;
    errorBanner: CSSProperties;
    reviewBox: CSSProperties;
    reviewHeader: CSSProperties;
    reviewLabel: CSSProperties;
    reviewValue: CSSProperties;
    helpFooter: CSSProperties;
    toggleBtn: (active: boolean, color?: string) => CSSProperties;
    iconBtn: CSSProperties;
};
//# sourceMappingURL=formStyles.d.ts.map