// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'btnAvancar': string;

  'btnSubmit': string;

  'btnVoltar': string;

  'button': string;

  'description': string;

  'formContainer': string;

  'formInput': string;

  'formularioMaquinas': string;

  'greenTitle': string;

  'headerCard': string;

  'helpText': string;

  'importantBox': string;

  'logoPHS': string;

  'menuPrincipal': string;

  'navigationButtons': string;

  'qLabel': string;

  'qNumber': string;

  'questionGroup': string;

  'radioOptions': string;

  'sectionCard': string;

  'sectionTab': string;

  'teams': string;

  'tipoExclusao': string;

  'tipoNovoUsuario': string;

  'tipoSubstituicao': string;

  'title': string;

}

declare const strings: IExportStyles;

export default strings;